# Default user: neo4j, password is 123456

version: '3.8'
services:

  neo4j:
    container_name: ${APP_NAME}
    image: neo4j:${DB_NEO4J_VERSION}
    environment:
    #   SECURE_FILE_PERMISSIONS=yes
     - NEO4J_AUTH=${DB_NEO4J_USER}/${DB_NEO4J_PASSWORD}
    ports:
     - ${DB_NEO4J_PORT}:7687
     - ${APP_PORT}:7474
    restart: always
    volumes:
     - neo4j_data:/var/lib/neo4j/data
     - neo4j_logs:/var/lib/neo4j/logs
     - neo4j_conf:/var/lib/neo4j/conf
     - neo4j_plugins:/var/lib/neo4j/plugins
  
networks:
  default:
    name: ${APP_NAME}
    
volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_conf:
  neo4j_plugins:
