# Default user: neo4j, password is 123456

version: '3.8'
services:

  neo4j:
    container_name: ${APP_NAME}
    image: neo4j:${APP_VERSION}
    environment:
    #   SECURE_FILE_PERMISSIONS=yes
     - NEO4J_AUTH=neo4j/123456
    ports:
     - 7474:7474
     - 7687:7687
    restart: always
    volumes:
     - neo4j_data:/data
     - neo4j_logs:/logs
     - neo4j_conf:/conf
     - neo4j_plugins:/plugins
  
networks:
  default:
    name: ${APP_NAME}
    
volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_conf:
  neo4j_plugins:
