# Default user: neo4j, password is 123456

version: '3.8'
services:

  neo4j:
    container_name: ${APP_CONTAINER_NAME}
    image: neo4j:${APP_VERSION}
    environment:
    #   SECURE_FILE_PERMISSIONS=yes
     - NEO4J_AUTH=neo4j/123456
    ports:
     - 7474:7474
     - 7687:7687
    restart: always
    volumes:
     - ${VOLUMES_PATH_PREFIX}/neo4j/data:/data
     - ${VOLUMES_PATH_PREFIX}/neo4j/logs:/logs
     - ${VOLUMES_PATH_PREFIX}/neo4j/conf:/conf
     - ${VOLUMES_PATH_PREFIX}/neo4j/plugins:/plugins
  
networks:
  default:
    name: ${APP_NETWORK}